<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tungnn.tutor.java.tool</groupId>
        <artifactId>crawler-tool</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>crawler-tool-app</artifactId>

    <name>crawler-tool-app</name>
    <description>crawler-tool-app</description>

    <properties>
        <java.version>25</java.version>
        <spring-shell.version>4.0.2</spring-shell.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>tungnn.tutor.java.tool</groupId>
            <artifactId>crawler-tool-core</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.shell</groupId>
                <artifactId>spring-shell-dependencies</artifactId>
                <version>${spring-shell.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
